/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

/**
 *
 * @author vinicio
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tableAddDialog = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        tableAddName = new javax.swing.JTextField();
        tableAddType = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        tableAddOrg = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tableAddLength = new javax.swing.JSpinner();
        tableAddFields = new javax.swing.JComboBox<>();
        tableAddField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tableAddFieldAdd = new javax.swing.JButton();
        tableAddFieldRemove = new javax.swing.JButton();
        tableAddSave = new javax.swing.JButton();
        tableUpdateDialog = new javax.swing.JDialog();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tableUpdateFieldAdd = new javax.swing.JButton();
        tableUpdateFieldRemove = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tableUpdateName = new javax.swing.JTextField();
        tableUpdateType = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        tableUpdateLength = new javax.swing.JSpinner();
        tableUpdateFields = new javax.swing.JComboBox<>();
        tableUpdateField = new javax.swing.JTextField();
        tableUpdateOrg = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableUpdateRegistryTable = new javax.swing.JTable();
        tableUpdateSelectedTable = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        tableUpdateGuardar = new javax.swing.JButton();
        tableDeleteDialog = new javax.swing.JDialog();
        talbeDeleteNode = new javax.swing.JComboBox<>();
        tableDeleteDelete = new javax.swing.JButton();
        tablePopupMenu = new javax.swing.JPopupMenu();
        tableAddMenuItem = new javax.swing.JMenuItem();
        tableUpdateMenuItem = new javax.swing.JMenuItem();
        tableDeleteMenuItem = new javax.swing.JMenuItem();
        relationAddDialog = new javax.swing.JDialog();
        relationAddA = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        relationAddB = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        relationAddType = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        relationAddSave = new javax.swing.JButton();
        relationUpdateDialog = new javax.swing.JDialog();
        relationUpdateBase = new javax.swing.JComboBox<>();
        relationUpdateA = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        relationUpdateType = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        relationUpdateB = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        relationUpdateSave = new javax.swing.JButton();
        relationDeleteDialog = new javax.swing.JDialog();
        relationDeleteNode = new javax.swing.JComboBox<>();
        relationDeleteDelete = new javax.swing.JButton();
        relationPopupMenu = new javax.swing.JPopupMenu();
        relationAddMenuItem = new javax.swing.JMenuItem();
        relationUpdateMenuItem = new javax.swing.JMenuItem();
        relationDeleteMenuItem = new javax.swing.JMenuItem();
        viewDiagramDialog = new javax.swing.JDialog();
        tableManager = new javax.swing.JButton();
        relationManager = new javax.swing.JButton();
        diagramViewer = new javax.swing.JButton();

        jLabel1.setText("Nombre");

        tableAddType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fijo", "Variable" }));

        jLabel2.setText("Longitud de Campos");

        tableAddOrg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FIjar la Longitud del Campo", "Iniciar el Campo con un Indicador" }));

        jLabel3.setText("TIpo de Organizacion");

        jLabel4.setText("Longitud");

        tableAddLength.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jLabel11.setText("Agregar Campo");

        jLabel12.setText("Campos");

        tableAddFieldAdd.setText("Agregar");

        tableAddFieldRemove.setText("Eliminar");

        tableAddSave.setText("Guardar");

        javax.swing.GroupLayout tableAddDialogLayout = new javax.swing.GroupLayout(tableAddDialog.getContentPane());
        tableAddDialog.getContentPane().setLayout(tableAddDialogLayout);
        tableAddDialogLayout.setHorizontalGroup(
            tableAddDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tableAddDialogLayout.createSequentialGroup()
                .addGroup(tableAddDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tableAddDialogLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(tableAddDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tableAddDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tableAddFields, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tableAddLength)
                            .addComponent(tableAddOrg, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tableAddType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tableAddName)
                            .addComponent(tableAddField, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(tableAddDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tableAddFieldAdd)
                            .addComponent(tableAddFieldRemove)))
                    .addGroup(tableAddDialogLayout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(tableAddSave)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tableAddDialogLayout.setVerticalGroup(
            tableAddDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tableAddDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tableAddDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tableAddName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tableAddDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tableAddType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(tableAddDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tableAddOrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(tableAddDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tableAddLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(tableAddDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tableAddField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(tableAddFieldAdd))
                .addGap(18, 18, 18)
                .addGroup(tableAddDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tableAddFields, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(tableAddFieldRemove))
                .addGap(18, 18, 18)
                .addComponent(tableAddSave)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel13.setText("TIpo de Organizacion");

        jLabel14.setText("Campos");

        tableUpdateFieldAdd.setText("Agregar");

        tableUpdateFieldRemove.setText("Eliminar");

        jLabel15.setText("Longitud");

        jLabel16.setText("Nombre");

        tableUpdateType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fijo", "Variable" }));

        jLabel17.setText("Longitud de Campos");

        tableUpdateLength.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        tableUpdateOrg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FIjar la Longitud del Campo", "Iniciar el Campo con un Indicador" }));

        jLabel18.setText("Agregar Campo");

        tableUpdateRegistryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tableUpdateRegistryTable);
        if (tableUpdateRegistryTable.getColumnModel().getColumnCount() > 0) {
            tableUpdateRegistryTable.getColumnModel().getColumn(0).setResizable(false);
            tableUpdateRegistryTable.getColumnModel().getColumn(1).setResizable(false);
            tableUpdateRegistryTable.getColumnModel().getColumn(2).setResizable(false);
            tableUpdateRegistryTable.getColumnModel().getColumn(3).setResizable(false);
            tableUpdateRegistryTable.getColumnModel().getColumn(4).setResizable(false);
            tableUpdateRegistryTable.getColumnModel().getColumn(5).setResizable(false);
            tableUpdateRegistryTable.getColumnModel().getColumn(6).setResizable(false);
            tableUpdateRegistryTable.getColumnModel().getColumn(7).setResizable(false);
            tableUpdateRegistryTable.getColumnModel().getColumn(8).setResizable(false);
            tableUpdateRegistryTable.getColumnModel().getColumn(9).setResizable(false);
            tableUpdateRegistryTable.getColumnModel().getColumn(10).setResizable(false);
            tableUpdateRegistryTable.getColumnModel().getColumn(11).setResizable(false);
            tableUpdateRegistryTable.getColumnModel().getColumn(12).setResizable(false);
        }

        jLabel19.setText("Table");

        tableUpdateGuardar.setText("Guardar");

        javax.swing.GroupLayout tableUpdateDialogLayout = new javax.swing.GroupLayout(tableUpdateDialog.getContentPane());
        tableUpdateDialog.getContentPane().setLayout(tableUpdateDialogLayout);
        tableUpdateDialogLayout.setHorizontalGroup(
            tableUpdateDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tableUpdateDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tableUpdateDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(tableUpdateDialogLayout.createSequentialGroup()
                        .addGroup(tableUpdateDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel13)
                            .addComponent(jLabel15)
                            .addComponent(jLabel18)
                            .addComponent(jLabel14)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tableUpdateDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tableUpdateDialogLayout.createSequentialGroup()
                                .addGroup(tableUpdateDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tableUpdateFields, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tableUpdateLength)
                                    .addComponent(tableUpdateOrg, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tableUpdateType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tableUpdateName)
                                    .addComponent(tableUpdateField, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(tableUpdateDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tableUpdateFieldAdd)
                                    .addComponent(tableUpdateFieldRemove))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(tableUpdateSelectedTable, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(tableUpdateDialogLayout.createSequentialGroup()
                .addGap(312, 312, 312)
                .addComponent(tableUpdateGuardar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tableUpdateDialogLayout.setVerticalGroup(
            tableUpdateDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tableUpdateDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tableUpdateDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tableUpdateSelectedTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addGroup(tableUpdateDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(tableUpdateName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tableUpdateDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tableUpdateType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(tableUpdateDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tableUpdateOrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(tableUpdateDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tableUpdateLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(tableUpdateDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tableUpdateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(tableUpdateFieldAdd))
                .addGap(18, 18, 18)
                .addGroup(tableUpdateDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tableUpdateFields, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(tableUpdateFieldRemove))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tableUpdateGuardar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tableDeleteDelete.setText("Eliminar");

        javax.swing.GroupLayout tableDeleteDialogLayout = new javax.swing.GroupLayout(tableDeleteDialog.getContentPane());
        tableDeleteDialog.getContentPane().setLayout(tableDeleteDialogLayout);
        tableDeleteDialogLayout.setHorizontalGroup(
            tableDeleteDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tableDeleteDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tableDeleteDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(talbeDeleteNode, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tableDeleteDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tableDeleteDialogLayout.setVerticalGroup(
            tableDeleteDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tableDeleteDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(talbeDeleteNode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tableDeleteDelete)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tableAddMenuItem.setText("Agregar Tabla");
        tableAddMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tableAddMenuItemActionPerformed(evt);
            }
        });
        tablePopupMenu.add(tableAddMenuItem);

        tableUpdateMenuItem.setText("Modificar Tabla");
        tableUpdateMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tableUpdateMenuItemActionPerformed(evt);
            }
        });
        tablePopupMenu.add(tableUpdateMenuItem);

        tableDeleteMenuItem.setText("Eliminar Tabla");
        tableDeleteMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tableDeleteMenuItemActionPerformed(evt);
            }
        });
        tablePopupMenu.add(tableDeleteMenuItem);

        jLabel5.setText("A");

        jLabel6.setText("B");

        relationAddType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Uno a Uno", "Uno a Varios", "Varios a Uno", "Varios a Varios" }));

        jLabel7.setText("Tipo de Relacion");

        relationAddSave.setText("Guardar");

        javax.swing.GroupLayout relationAddDialogLayout = new javax.swing.GroupLayout(relationAddDialog.getContentPane());
        relationAddDialog.getContentPane().setLayout(relationAddDialogLayout);
        relationAddDialogLayout.setHorizontalGroup(
            relationAddDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(relationAddDialogLayout.createSequentialGroup()
                .addGroup(relationAddDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(relationAddDialogLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(relationAddDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(relationAddDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(relationAddB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(relationAddType, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(relationAddA, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(relationAddDialogLayout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(relationAddSave)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        relationAddDialogLayout.setVerticalGroup(
            relationAddDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(relationAddDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(relationAddDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(relationAddA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(relationAddDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(relationAddType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(relationAddDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(relationAddB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(relationAddSave)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        relationUpdateBase.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        relationUpdateA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel8.setText("A");

        relationUpdateType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel9.setText("Tipo de Relacion");

        relationUpdateB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel10.setText("B");

        relationUpdateSave.setText("Guardar");

        javax.swing.GroupLayout relationUpdateDialogLayout = new javax.swing.GroupLayout(relationUpdateDialog.getContentPane());
        relationUpdateDialog.getContentPane().setLayout(relationUpdateDialogLayout);
        relationUpdateDialogLayout.setHorizontalGroup(
            relationUpdateDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(relationUpdateDialogLayout.createSequentialGroup()
                .addGroup(relationUpdateDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(relationUpdateDialogLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(relationUpdateDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(relationUpdateBase, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(relationUpdateDialogLayout.createSequentialGroup()
                                .addGroup(relationUpdateDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(relationUpdateDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(relationUpdateB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(relationUpdateType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(relationUpdateA, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(relationUpdateDialogLayout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(relationUpdateSave)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        relationUpdateDialogLayout.setVerticalGroup(
            relationUpdateDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(relationUpdateDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(relationUpdateBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(relationUpdateDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(relationUpdateA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(relationUpdateDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(relationUpdateType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(relationUpdateDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(relationUpdateB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addComponent(relationUpdateSave)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        relationDeleteDelete.setText("Eliminar");

        javax.swing.GroupLayout relationDeleteDialogLayout = new javax.swing.GroupLayout(relationDeleteDialog.getContentPane());
        relationDeleteDialog.getContentPane().setLayout(relationDeleteDialogLayout);
        relationDeleteDialogLayout.setHorizontalGroup(
            relationDeleteDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(relationDeleteDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(relationDeleteDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(relationDeleteNode, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(relationDeleteDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        relationDeleteDialogLayout.setVerticalGroup(
            relationDeleteDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(relationDeleteDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(relationDeleteNode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(relationDeleteDelete)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        relationAddMenuItem.setText("Agregar Relacion");
        relationAddMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relationAddMenuItemActionPerformed(evt);
            }
        });
        relationPopupMenu.add(relationAddMenuItem);

        relationUpdateMenuItem.setText("Modificar Relacion");
        relationUpdateMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relationUpdateMenuItemActionPerformed(evt);
            }
        });
        relationPopupMenu.add(relationUpdateMenuItem);

        relationDeleteMenuItem.setText("Eliminar Relacion");
        relationDeleteMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relationDeleteMenuItemActionPerformed(evt);
            }
        });
        relationPopupMenu.add(relationDeleteMenuItem);

        javax.swing.GroupLayout viewDiagramDialogLayout = new javax.swing.GroupLayout(viewDiagramDialog.getContentPane());
        viewDiagramDialog.getContentPane().setLayout(viewDiagramDialogLayout);
        viewDiagramDialogLayout.setHorizontalGroup(
            viewDiagramDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        viewDiagramDialogLayout.setVerticalGroup(
            viewDiagramDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tableManager.setText("Tablas");
        tableManager.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableManagerMouseClicked(evt);
            }
        });

        relationManager.setText("Relaciones");
        relationManager.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                relationManagerMouseClicked(evt);
            }
        });

        diagramViewer.setText("Ver Diagrama");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(diagramViewer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tableManager, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(relationManager, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tableManager)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(relationManager)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(diagramViewer)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableManagerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableManagerMouseClicked
        this.tablePopupMenu.show(evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_tableManagerMouseClicked

    private void tableAddMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tableAddMenuItemActionPerformed
        this.tableAddDialog.pack();
        this.tableAddDialog.setModal(true);
        this.tableAddDialog.setVisible(true);
    }//GEN-LAST:event_tableAddMenuItemActionPerformed

    private void tableUpdateMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tableUpdateMenuItemActionPerformed
        this.tableUpdateDialog.pack();
        this.tableUpdateDialog.setModal(true);
        this.tableUpdateDialog.setVisible(true);
    }//GEN-LAST:event_tableUpdateMenuItemActionPerformed

    private void tableDeleteMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tableDeleteMenuItemActionPerformed
        this.tableDeleteDialog.pack();
        this.tableDeleteDialog.setModal(true);
        this.tableDeleteDialog.setVisible(true);
    }//GEN-LAST:event_tableDeleteMenuItemActionPerformed

    private void relationManagerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_relationManagerMouseClicked
        this.relationPopupMenu.show(evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_relationManagerMouseClicked

    private void relationAddMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relationAddMenuItemActionPerformed
        this.relationAddDialog.pack();
        this.relationAddDialog.setModal(true);
        this.relationAddDialog.setVisible(true);
    }//GEN-LAST:event_relationAddMenuItemActionPerformed

    private void relationUpdateMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relationUpdateMenuItemActionPerformed
        this.relationUpdateDialog.pack();
        this.relationUpdateDialog.setModal(true);
        this.relationUpdateDialog.setVisible(true);
    }//GEN-LAST:event_relationUpdateMenuItemActionPerformed

    private void relationDeleteMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relationDeleteMenuItemActionPerformed
        this.relationDeleteDialog.pack();
        this.relationDeleteDialog.setModal(true);
        this.relationDeleteDialog.setVisible(true);
    }//GEN-LAST:event_relationDeleteMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton diagramViewer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> relationAddA;
    private javax.swing.JComboBox<String> relationAddB;
    private javax.swing.JDialog relationAddDialog;
    private javax.swing.JMenuItem relationAddMenuItem;
    private javax.swing.JButton relationAddSave;
    private javax.swing.JComboBox<String> relationAddType;
    private javax.swing.JButton relationDeleteDelete;
    private javax.swing.JDialog relationDeleteDialog;
    private javax.swing.JMenuItem relationDeleteMenuItem;
    private javax.swing.JComboBox<String> relationDeleteNode;
    private javax.swing.JButton relationManager;
    private javax.swing.JPopupMenu relationPopupMenu;
    private javax.swing.JComboBox<String> relationUpdateA;
    private javax.swing.JComboBox<String> relationUpdateB;
    private javax.swing.JComboBox<String> relationUpdateBase;
    private javax.swing.JDialog relationUpdateDialog;
    private javax.swing.JMenuItem relationUpdateMenuItem;
    private javax.swing.JButton relationUpdateSave;
    private javax.swing.JComboBox<String> relationUpdateType;
    private javax.swing.JDialog tableAddDialog;
    private javax.swing.JTextField tableAddField;
    private javax.swing.JButton tableAddFieldAdd;
    private javax.swing.JButton tableAddFieldRemove;
    private javax.swing.JComboBox<String> tableAddFields;
    private javax.swing.JSpinner tableAddLength;
    private javax.swing.JMenuItem tableAddMenuItem;
    private javax.swing.JTextField tableAddName;
    private javax.swing.JComboBox<String> tableAddOrg;
    private javax.swing.JButton tableAddSave;
    private javax.swing.JComboBox<String> tableAddType;
    private javax.swing.JButton tableDeleteDelete;
    private javax.swing.JDialog tableDeleteDialog;
    private javax.swing.JMenuItem tableDeleteMenuItem;
    private javax.swing.JButton tableManager;
    private javax.swing.JPopupMenu tablePopupMenu;
    private javax.swing.JDialog tableUpdateDialog;
    private javax.swing.JTextField tableUpdateField;
    private javax.swing.JButton tableUpdateFieldAdd;
    private javax.swing.JButton tableUpdateFieldRemove;
    private javax.swing.JComboBox<String> tableUpdateFields;
    private javax.swing.JButton tableUpdateGuardar;
    private javax.swing.JSpinner tableUpdateLength;
    private javax.swing.JMenuItem tableUpdateMenuItem;
    private javax.swing.JTextField tableUpdateName;
    private javax.swing.JComboBox<String> tableUpdateOrg;
    private javax.swing.JTable tableUpdateRegistryTable;
    private javax.swing.JComboBox<String> tableUpdateSelectedTable;
    private javax.swing.JComboBox<String> tableUpdateType;
    private javax.swing.JComboBox<String> talbeDeleteNode;
    private javax.swing.JDialog viewDiagramDialog;
    // End of variables declaration//GEN-END:variables
}
